$mainMod = $SUPER # Sets "Windows" key as main modifier

##### Commands #####
bind=$mainMod,RETURN,exec,$terminal
bind=$mainMod SHIFT,q,killactive,
bind=$mainMod,space,exec,$menu
bind=$mainMod,f,fullscreen

## Media keys ##
bind=,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
binde=,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
binde=,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binde=,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

## Keybard Layout ##
bind=SHIFT_L,ALT_L,exec,sh $HOME/.config/hypr/scripts/toggle_keymap.sh keymapToggle

## Screen Brightness ##
binde=,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 3%+
binde=,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 3%-

## keyboard Brightness ##
binde=SHIFT,XF86MonBrightnessUp, exec, brightnessctl --device="tpacpi::kbd_backlight" set 1+
binde=SHIFT,XF86MonBrightnessDown, exec, brightnessctl --device="tpacpi::kbd_backlight" set 1-

## Screen Commands ##
bind=$mainMod,s,exec,snip # look for a snipping tool app
bind=CTRL_SHIFT,Escape,exec,hyprlock # lock screen, look for a cool locker. Maybe a login manager?

## Focus window
bind=$mainMod,h,movefocus,l
bind=$mainMod,l,movefocus,r
bind=$mainMod,j,movefocus,d
bind=$mainMod,k,movefocus,u

## Move window
bind=$mainMod SHIFT,h,movewindow,l
bind=$mainMod SHIFT,l,movewindow,r
bind=$mainMod SHIFT,j,movewindow,d
bind=$mainMod SHIFT,k,movewindow,u
bindm=$mainMod,mouse:272,movewindow # mouse movement, just in case

## Select Workspace
bind=$mainMod,1,workspace,1
bind=$mainMod,2,workspace,2
bind=$mainMod,3,workspace,3
bind=$mainMod,4,workspace,4
bind=$mainMod,5,workspace,5
bind=$mainMod,6,workspace,6
bind=$mainMod,7,workspace,7
bind=$mainMod,8,workspace,8
bind=$mainMod,9,workspace,9

## Focus Workspace
bind=$mainMod SHIFT,1,movetoworkspace,1
bind=$mainMod SHIFT,2,movetoworkspace,2
bind=$mainMod SHIFT,2,movetoworkspace,2
bind=$mainMod SHIFT,2,movetoworkspace,2
bind=$mainMod SHIFT,3,movetoworkspace,3
bind=$mainMod SHIFT,4,movetoworkspace,4
bind=$mainMod SHIFT,5,movetoworkspace,5
bind=$mainMod SHIFT,6,movetoworkspace,6
bind=$mainMod SHIFT,7,movetoworkspace,7
bind=$mainMod SHIFT,8,movetoworkspace,8
bind=$mainMod SHIFT,9,movetoworkspace,9

## Resize mode
bind=$mainMod,R,submap,resize # switches to a submap named resize
submap=resize # start here the resize submap
bind=,l,resizeactive,10 0
bind=,h,resizeactive,-10 0
bind=,k,resizeactive,0 -10
bind=,j,resizeactive,0 10
bind=,Escape,submap,reset # leave resize mode
submap=reset # reset the submap back to default
