# black
color0 #000000
color8 #767676

# red
color1 #cc0403
color9 #f27070

# green
color2 #70b270 
color10 #20ff20

# yellow
color3 #aaaa00
color11 #ffff20

# blue
color4 #7a7aff
color12 #2d23fc

# magenta
color5 #cb1ed1
color12 #fd28ff

# cyan
color6 #0dcdcd
color14 #14ffff

# white
color7 #aaaaaa
color15 #ffffff
